export default {
  meta: {
    series: '나만 몰랐던 일본',
    number: '001',
    episode: '히다 편',
    tag: '#나만몰랐던일본',
    watermark: '숲길따라 감성여행',
    photoStatus: 'placeholder',
    photoNote: '생성형 AI 연출 이미지입니다. 실제 히다 현지 촬영 원본으로 교체 전에는 새 게시·재게시할 수 없습니다.',
    landing: {
      profileUrl: 'https://foresttour.kr/',
      storyPath: '/stories/hida',
      sources: {
        carousel: 'insta-carousel-hida',
        story: 'insta-story-hida',
        reel: 'insta-reel-hida',
      },
      connectedTour: null,
    },
  },
  cards: [
    {
      id: 'cover-a',
      kind: 'cover',
      title: '가이드북엔 없는<br>진짜 일본을 찾는다면',
      sub: '나만 몰랐던 일본 001 — 히다(飛騨)',
      photo: 'cardnews/photos/hida/cover-a.jpg',
    },
    {
      id: '02-oldtown',
      kind: 'pc',
      eye: '01 · 에도 성하·상인 마을',
      title: '거리 전체에 남은<br>에도 시대의 시간',
      body: '다카야마의 오래된 거리는 성하마을과 상인 마을로 발달했습니다.<br>보존지구의 격자창과 낮은 처마,<br>처마 아래 용수로가 한 길로 이어집니다.',
      hand: '— 한 건물보다 거리 전체를 걷는 곳',
      photo: 'cardnews/photos/hida/02-train.jpg',
    },
    {
      id: '03-gassho',
      kind: 'pc',
      eye: '02 · 갓쇼즈쿠리',
      title: '많은 눈을 견디도록<br>가파르게 세운 지붕',
      body: '기후현 시라카와고의 급경사 억새 지붕.<br>큰 다락은 누에를 기르던 생활과 연결됐습니다.<br>도야마현 고카야마는 같은 세계유산이지만 다른 지역입니다.',
      hand: '— 눈과 생활이 함께 만든 산촌의 구조',
      photo: 'cardnews/photos/hida/03-sand.jpg',
    },
    {
      id: '04-onsen',
      kind: 'pc',
      eye: '03 · 일본 삼명천',
      title: '히다강 곁에서 만나는<br>게로의 온천수',
      body: '공식 관광정보가 소개하는 약 1,000년의 역사.<br>알칼리성 단순온천의 매끄러운 촉감이<br>오래된 거리와 산마을을 걸은 하루를 잇습니다.',
      hand: '— 산마을의 하루를 천천히 닫는 물',
      photo: 'cardnews/photos/hida/04-cliff.jpg',
    },
    {
      id: '05-beef',
      kind: 'pc',
      eye: '04 · 기후현 브랜드 와규',
      title: '이름보다 먼저 확인할<br>히다규 인증 표지',
      body: '기후현 인정 생산자가 14개월 이상 기른 흑모화우 가운데<br>공식 육질 기준을 통과한 고기에 히다규 표지가 붙습니다.<br>생산자와 개체 정보까지 표지에서 확인할 수 있습니다.',
      hand: '— 이름이 아니라 인증 기준으로 만나는 지역의 맛',
      photo: 'cardnews/photos/hida/05-jodo.jpg',
    },
    {
      id: '06-walk',
      kind: 'paper',
      eye: '05 · FIELD NOTE',
      title: '히다 마을을 가장 깊게<br>느끼며 걷는 시간',
      body: '· 아침 일찍 미야가와 강변 시장 천천히 보기<br>· 격자창과 용수로를 따라 오래된 거리 걷기<br>· 산마을을 읽은 뒤 게로 온천에서 하루 마무리',
      hand: '— 한 마을을 오래 보는 하루의 순서',
    },
    {
      id: '07-outro',
      kind: 'paper',
      stamp: '001<br>히다',
      eye: '나만 몰랐던 일본 — 001 히다. 끝.',
      title: '소개할 만큼 아름다워<br>우리가 길을 만듭니다',
      body: '카드에 다 담지 못한 위치와 이유는<br>foresttour.kr의 히다 기록에서 더 천천히 이어집니다.',
      hand: '— 프로필 링크에서 이야기를 이어갑니다',
    },
  ],
};
