export default {
  meta: {
    series: '나만 몰랐던 일본',
    number: '001',
    episode: '히다 편',
    tag: '#나만몰랐던일본',
    watermark: '숲길따라 감성여행',
  },
  cards: [
    {
      id: 'cover-a',
      kind: 'cover',
      title: '가이드북엔 없는<br>진짜 일본을 찾는다면',
      sub: '나만 몰랐던 일본 001 — 히다(飛騨)',
      photo: 'cardnews/photos/hida/cover-a.jpg',
    },
    {
      id: '02-oldtown',
      kind: 'pc',
      eye: '01 · 에도 시대의 미로',
      title: '에도 시대 격자창이 그대로,<br>작은 교토라 불리는 땅',
      body: '산에 둘러싸인 작은 마을 산마치에 들어서는 순간,<br>백 년 전 목조 가옥들이 길게 이어집니다.<br>낮은 처마 아래로 맑은 물소리가 흐르는 거리.',
      hand: '— 백 년의 정취가 살아있는 거리',
      photo: 'cardnews/photos/hida/02-train.jpg',
    },
    {
      id: '03-gassho',
      kind: 'pc',
      eye: '02 · 갓쇼후쿠리',
      title: '눈의 무게를 견디는<br>억새 지붕 집들의 비밀',
      body: '기도하듯 손을 모은 모양의 갓쇼 지붕.<br>못 하나 쓰지 않고 나무와 억새로 엮어낸 생존의 건축,<br>겨울이면 수직으로 솟아오른 듯 유연한 풍경.',
      hand: '— 눈 깊은 산골의 지혜가 담긴 마을',
      photo: 'cardnews/photos/hida/03-sand.jpg',
    },
    {
      id: '04-onsen',
      kind: 'pc',
      eye: '03 · 3대 명천',
      title: '일본 3대 명천,<br>게로 온천의 부드러운 유질',
      body: '천 년 넘게 미끈거리는 알칼리 온천수가 샘솟는 곳.<br>천연 미용수로 불릴 만큼 부드럽게 감싸는 피부,<br>밤이면 강변을 따라 따뜻한 김이 피어오릅니다.',
      hand: '— 몸과 마음이 사르르 녹아내리는 밤',
      photo: 'cardnews/photos/hida/04-cliff.jpg',
    },
    {
      id: '05-beef',
      kind: 'pc',
      eye: '04 · 히다규',
      title: '입안에서 녹아내리는<br>최고급 히다규의 풍미',
      body: '청정 맑은 물과 풀을 먹고 자란 최고의 흑우.<br>마블링이 촘촘한 히다규 덮밥과 꼬치 한 입,<br>여행의 고단함을 잊게 만드는 깊은 감칠맛.',
      hand: '— 이 땅에서 꼭 맛봐야 할 별미',
      photo: 'cardnews/photos/hida/05-jodo.jpg',
    },
    {
      id: '06-walk',
      kind: 'paper',
      eye: '05 · FIELD NOTE',
      title: '히다 마을을 가장 깊게<br>느끼며 걷는 시간',
      body: '· 아침 일찍 미야가와 아침시장에서 장보기<br>· 에도 골목길에서 갓 구운 당고 한 입<br>· 산책 후 게로 온천에서 족욕으로 마무리',
      hand: '— 일정표에 적힌 것이 전부인 3박 4일 히다 여행',
    },
    {
      id: '07-outro',
      kind: 'paper',
      stamp: '001<br>히다',
      eye: '나만 몰랐던 일본 — 001 히다. 끝.',
      title: '소개할 만큼 아름다워<br>우리가 길을 만듭니다',
      body: '나만 몰랐던 일본의 진짜 이야기를 숲길과 함께.<br>자세한 여행 일정과 출발일은 프로필 링크에서 확인하세요.',
      hand: '— 이 정취는 10월에 실제로 만납니다 · 프로필에서',
    },
  ],
};
